export const defaultTheme = {
    'white': '#FFFFFF',
    'background': '#FAFAFA',
    'base-card': '#F3F2F2',
    'base-input': '#EDEDED',
    'base-button': '#E6E5E5',
    'base-hover': '#D7D5D5',
    'base-label': '#8D8686',
    'base-text': '#574F4D',
    'base-subtitle': '#403937',
    'base-title': '#272221',

    'yellow': '#DBAC2C',
    'yellow-dark': '#C47F17',
    'yellow-light': '#F1E9C9',
    'yellow-hover': '#ebe2be',
    'purple': '#8047F8',
    'purple-dark': '#4B2995',
    'purple-light': '#EBE5F9',
    'purple-hover': '#e3dcf4',

    'title-xl': '2.5rem',
    'title-l': '2rem',
    'title-m': '1.5rem',
    'title-s': '1.25rem',
    'title-xs': '1.125rem',
    'text-l': '1.25rem',
    'text-m': '1rem',
    'text-s': '0.875rem',
    'text-xs': '0.75rem',
    'tag': '0.625rem',
    'button-large': '0.875rem',
    'button-small': '0.75rem',

    'lineHeight-normal': '130%',
    'lineHeight-large': '160%',
}